import type { Metadata } from "next";
import "./globals.css";
import { AuthContext } from "@/hooks/AuthContext";

export const metadata: Metadata = {
  title: "Netflix Clone",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="ja">
      <body>
        <AuthContext>{children}</AuthContext>
      </body>
    </html>
  );
}
